name: metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_languages_details: bytes-size
          plugin_languages_indepth: no
          plugin_languages_sections: chart-donut
